import NamespaceApplication from "./NamespaceApplication";
import Util from "./util";
import Cookie from "./cookie";
import Storage from "./storage";
import SessionStorage from "./session-storage";
import Datetime from "./datetime";
import EventManager from "./event-manager";
import Timer from "./timer";
import Emmet from "./emmet";
import httpRequest from "./http-request";
import Dom from "./dom";
import Str from "./str";
import Arr from "./arr";
import Roxy from "./roxy";
import {RoxyListener} from "./roxy";


window.NamespaceApplication = NamespaceApplication;
window.NamespaceApplication.Util = Util;
window.NamespaceApplication.Cookie = Cookie;
window.NamespaceApplication.Storage = Storage;
window.NamespaceApplication.SessionStorage = SessionStorage;
window.NamespaceApplication.Datetime = Datetime;
window.NamespaceApplication.EventManager = EventManager;
window.NamespaceApplication.Timer = Timer;
window.NamespaceApplication.Emmet = Emmet;
window.NamespaceApplication.httpRequest = httpRequest;
window.NamespaceApplication.Dom = Dom;
window.NamespaceApplication.Str = Str;
window.NamespaceApplication.Arr = Arr;
window.NamespaceApplication.Roxy = Roxy;
window.NamespaceApplication.RoxyListener = RoxyListener;
window.Ns = window.NamespaceApplication;